In [33]:
import pandas as pd
import numpy as np

In [34]:
data = pd.read_csv("netflix_titles.csv", encoding='iso-8859-1')

data.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,...,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [35]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8809 entries, 0 to 8808
Data columns (total 26 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8809 non-null   object
 1   type          8809 non-null   object
 2   title         8809 non-null   object
 3   director      6175 non-null   object
 4   cast          7984 non-null   object
 5   country       7978 non-null   object
 6   date_added    8799 non-null   object
 7   release_year  8809 non-null   int64
 8   rating        8805 non-null   object
 9   duration      8806 non-null   object
 10  listed_in     8809 non-null   object
 11  description   8809 non-null   object
 12  Unnamed: 12   0 non-null      float64
 13  Unnamed: 13   0 non-null      float64
 14  Unnamed: 14   0 non-null      float64
 15  Unnamed: 15   0 non-null      float64
 16  Unnamed: 16   0 non-null      float64
 17  Unnamed: 17   0 non-null      float64
 18  Unnamed: 18   0 non-null      float64
 19  Unnamed: 19   0 non-null      float64
 20  Unnamed: 20   0 non-null      float64
 21  Unnamed: 21   0 non-null      float64
 22  Unnamed: 22   0 non-null      float64
 23  Unnamed: 23   0 non-null      float64
 24  Unnamed: 24   0 non-null      float64
 25  Unnamed: 25   0 non-null      float64
dtypes: float64(14), int64(1), object(11)
memory usage: 1.7+ MB

In [36]:
data.shape

(8809, 26)

In [37]:
movies = data.drop(columns=[col for col in data.columns if "Unnamed" in col])

In [38]:
movies.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [39]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8809 entries, 0 to 8808
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8809 non-null   object
 1   type          8809 non-null   object
 2   title         8809 non-null   object
 3   director      6175 non-null   object
 4   cast          7984 non-null   object
 5   country       7978 non-null   object
 6   date_added    8799 non-null   object
 7   release_year  8809 non-null   int64
 8   rating        8805 non-null   object
 9   duration      8806 non-null   object
 10  listed_in     8809 non-null   object
 11  description   8809 non-null   object
dtypes: int64(1), object(11)
memory usage: 826.0+ KB

In [40]:
movies.shape

(8809, 12)

In [41]:
movies['tags'] = (movies['director'] + ' ' + 
                  movies['cast'] + ' ' + 
                  movies['listed_in'] + ' ' + 
                  movies['description'])

In [42]:
movies.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,tags
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm...",NaN
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t...",NaN
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...,"Julien Leclercq Sami Bouajila, Tracy Gotoas, S..."
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo...",NaN
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...,NaN

In [43]:
movies = movies[['show_id', 'type', 'title', 'tags']]

movies

,show_id,type,title,tags
0,s1,Movie,Dick Johnson Is Dead,NaN
1,s2,TV Show,Blood & Water,NaN
2,s3,TV Show,Ganglands,"Julien Leclercq Sami Bouajila, Tracy Gotoas, S..."
3,s4,TV Show,Jailbirds New Orleans,NaN
4,s5,TV Show,Kota Factory,NaN
...,...,...,...,...
8804,s8805,Movie,Zombieland,"Ruben Fleischer Jesse Eisenberg, Woody Harrels..."
8805,s8806,Movie,Zoom,"Peter Hewitt Tim Allen, Courteney Cox, Chevy C..."
8806,s8807,Movie,Zubaan,"Mozez Singh Vicky Kaushal, Sarah-Jane Dias, Ra..."
8807,s8808,TV Show,Parasyte: The Grey,"Yeon Sang-ho Shin Hyun-been, Jeon Yeo-bin, Goo..."
8808,s8809,Movie,Serena,"Susanne Bier Bradley Cooper, Jennifer Lawrence..."

In [44]:
movies.dropna(inplace=True)

In [45]:
movies = movies.dropna()

In [46]:
movies

,show_id,type,title,tags
2,s3,TV Show,Ganglands,"Julien Leclercq Sami Bouajila, Tracy Gotoas, S..."
5,s6,TV Show,Midnight Mass,"Mike Flanagan Kate Siegel, Zach Gilford, Hamis..."
6,s7,Movie,My Little Pony: A New Generation,"Robert Cullen, JosÃƒÂ© Luis Ucha Vanessa Hudgens..."
7,s8,Movie,Sankofa,"Haile Gerima Kofi Ghanaba, Oyafunmike Ogunlano..."
8,s9,TV Show,The Great British Baking Show,"Andy Devonshire Mel Giedroyc, Sue Perkins, Mar..."
...,...,...,...,...
8804,s8805,Movie,Zombieland,"Ruben Fleischer Jesse Eisenberg, Woody Harrels..."
8805,s8806,Movie,Zoom,"Peter Hewitt Tim Allen, Courteney Cox, Chevy C..."
8806,s8807,Movie,Zubaan,"Mozez Singh Vicky Kaushal, Sarah-Jane Dias, Ra..."
8807,s8808,TV Show,Parasyte: The Grey,"Yeon Sang-ho Shin Hyun-been, Jeon Yeo-bin, Goo..."
8808,s8809,Movie,Serena,"Susanne Bier Bradley Cooper, Jennifer Lawrence..."

In [47]:
movies.reset_index(inplace=True, drop=True)

In [48]:
movies

,show_id,type,title,tags
0,s3,TV Show,Ganglands,"Julien Leclercq Sami Bouajila, Tracy Gotoas, S..."
1,s6,TV Show,Midnight Mass,"Mike Flanagan Kate Siegel, Zach Gilford, Hamis..."
2,s7,Movie,My Little Pony: A New Generation,"Robert Cullen, JosÃƒÂ© Luis Ucha Vanessa Hudgens..."
3,s8,Movie,Sankofa,"Haile Gerima Kofi Ghanaba, Oyafunmike Ogunlano..."
4,s9,TV Show,The Great British Baking Show,"Andy Devonshire Mel Giedroyc, Sue Perkins, Mar..."
...,...,...,...,...
5697,s8805,Movie,Zombieland,"Ruben Fleischer Jesse Eisenberg, Woody Harrels..."
5698,s8806,Movie,Zoom,"Peter Hewitt Tim Allen, Courteney Cox, Chevy C..."
5699,s8807,Movie,Zubaan,"Mozez Singh Vicky Kaushal, Sarah-Jane Dias, Ra..."
5700,s8808,TV Show,Parasyte: The Grey,"Yeon Sang-ho Shin Hyun-been, Jeon Yeo-bin, Goo..."
5701,s8809,Movie,Serena,"Susanne Bier Bradley Cooper, Jennifer Lawrence..."

In [49]:
from sklearn.feature_extraction.text import CountVectorizer

In [50]:
cv = CountVectorizer(max_features=5702, stop_words='english')

In [51]:
from sklearn.metrics.pairwise import cosine_similarity

In [52]:
vector = cv.fit_transform(movies['tags'].values.astype('U')).toarray()

In [53]:
similarity = cosine_similarity(vector)

In [54]:
similarity

array([[1.        , 0.21526419, 0.05564149, ..., 0.06024752, 0.0338255 ,
        0.0209427 ],
       [0.21526419, 1.        , 0.02528609, ..., 0.02737928, 0.03074377,
        0.01903467],
       [0.05564149, 0.02528609, 1.        , ..., 0.09553946, 0.03575993,
        0.02214037],
       ...,
       [0.06024752, 0.02737928, 0.09553946, ..., 1.        , 0.        ,
        0.02397317],
       [0.0338255 , 0.03074377, 0.03575993, ..., 0.        , 1.        ,
        0.        ],
       [0.0209427 , 0.01903467, 0.02214037, ..., 0.02397317, 0.        ,
        1.        ]])

In [55]:
movies[movies['title']=='Zubaan'].index[0]

5699

In [56]:
similarity[5699]

array([0.06024752, 0.02737928, 0.09553946, ..., 1.        , 0.        ,
       0.02397317])

In [57]:
similar_movies = sorted(list(enumerate(similarity[5699])), reverse=True, key= lambda vector: vector[1])

In [58]:
for i in similar_movies[1:6]: 
    print(movies.iloc[i[0]].title)
    print(i[1])

Jatts in Golmaal
0.32776066832815337
The Breakup Playlist
0.3103448275862069
Been So Long
0.3103448275862069
Evening Shadows
0.2913428162916919
Yaara O Dildaara
0.2913428162916919

In [59]:
def recommend_movie(movie_name): 
    movie_index = movies[movies['title'] == movie_name].index[0]
    similar_movies = sorted(list(enumerate(similarity[movie_index])), reverse=True, key= lambda vector: vector[1])
    for i in similar_movies[1:6]:
        similarity_percentage = round(i[1] * 100, 2)
        print(f'{movies.iloc[i[0]].title} is similar to {movie_name} with a similarity of {similarity_percentage}%.')

In [60]:
recommend_movie('Midnight Mass')

The Chosen One is similar to Midnight Mass with a similarity of 37.69%.
The Forest of Love: Deep Cut is similar to Midnight Mass with a similarity of 36.89%.
Goedam is similar to Midnight Mass with a similarity of 34.89%.
46 is similar to Midnight Mass with a similarity of 32.86%.
To the Lake is similar to Midnight Mass with a similarity of 32.3%.

In [66]:
import pickle as pkl

In [62]:
#!pip install bz2file

In [64]:
import bz2

In [68]:
with open('similarity.pkl', 'wb') as file:
    pkl.dump(similarity, file)

# Compress the pickle file
with open('similarity.pkl', 'rb') as file:
    with bz2.open('similarity.pkl.bz2', 'wb') as compressed_file:
        compressed_file.write(file.read())

In [69]:
import gzip

# Save and compress the model with gzip
with open('similarity.pkl', 'rb') as file:
    with gzip.open('similarity.pkl.gz', 'wb') as compressed_file:
        compressed_file.write(file.read())

In [70]:
import lzma

# Save and compress the model with lzma
with open('similarity.pkl', 'rb') as file:
    with lzma.open('similarity.pkl.xz', 'wb') as compressed_file:
        compressed_file.write(file.read())

In [ ]:
pkl.dump(movies, open('movies_dataset.pkl', 'wb'))

In [ ]:
#pkl.dump(similarity, open('similarity.pkl', 'wb'))